#!/usr/local/bin/perl

use Date::Parse;

open FILE, "mailq |";

our @times;

while(<FILE>) {
	next unless /^[A-Z0-9]+!/;
	my ($x, $y) = /^(\S+\s+){2}(.{19})/; 
	push @times, time - str2time($y);
}

close FILE;

our @arr = reverse sort { $a <=> $b } @times;
print $arr[0], "\n" if defined $arr[0];
print "0\n" if !defined $arr[0];

